services:
  postgres:
    image: postgres:16
    container_name: sun_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sun
    ports:
      - "5432:5432"